#ifndef MBEDTLS_PSA_CRYPTO_ASYNC_CONFIG_H
#define MBEDTLS_PSA_CRYPTO_ASYNC_CONFIG_H

#ifndef MBEDTLS_PSA_ASYNC_CRYPTO_HARDWARE_AVAILABLE
#define MBEDTLS_PSA_ASYNC_CRYPTO_HARDWARE_AVAILABLE 0
#endif

#if (defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_OFF) +                                                  \
    defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_SOFTWARE_ONLY) +                                        \
    defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID)) > 1
#error "Select at most one PSA crypto override: off, software-only, or hybrid"
#endif

#if !defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_OFF) && MBEDTLS_PSA_ASYNC_CRYPTO_HARDWARE_AVAILABLE &&  \
    !defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_SOFTWARE_ONLY)
#if !defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID)
#define MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HARDWARE_ONLY
#endif
#elif !defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_OFF)
#if defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID)
#undef MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID
#endif
#if !defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_SOFTWARE_ONLY)
#define MBEDTLS_PSA_ASYNC_CRYPTO_MODE_SOFTWARE_ONLY
#endif
#endif

#if defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HARDWARE_ONLY) ||                                        \
    defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID)
#define MBEDTLS_PSA_ASYNC_CRYPTO_HARDWARE_ENABLED 1
#else
#define MBEDTLS_PSA_ASYNC_CRYPTO_HARDWARE_ENABLED 0
#endif

#if defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_SOFTWARE_ONLY) ||                                        \
    defined(MBEDTLS_PSA_ASYNC_CRYPTO_MODE_HYBRID)
#define MBEDTLS_PSA_ASYNC_CRYPTO_SOFTWARE_ENABLED 1
#else
#define MBEDTLS_PSA_ASYNC_CRYPTO_SOFTWARE_ENABLED 0
#endif

#ifndef MBEDTLS_PSA_ASYNC_CRYPTO_MAX_CONCURRENT_OPERATIONS
#define MBEDTLS_PSA_ASYNC_CRYPTO_MAX_CONCURRENT_OPERATIONS 4
#endif

#if MBEDTLS_PSA_ASYNC_CRYPTO_MAX_CONCURRENT_OPERATIONS < 1
#error "MBEDTLS_PSA_ASYNC_CRYPTO_MAX_CONCURRENT_OPERATIONS must be at least one"
#endif

#endif /* MBEDTLS_PSA_CRYPTO_ASYNC_CONFIG_H */
