#!/usr/bin/env python3
"""Test the configuration checks generated by generate_config_checks.py.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import unittest

import scripts_path # pylint: disable=unused-import
from mbedtls_framework import unittest_config_checks


class CryptoTestConfigChecks(unittest_config_checks.TestConfigChecks):
    """TF-PSA-Crypto unit tests for config checks."""

    #pylint: disable=invalid-name # uppercase letters make sense here

    PROJECT_CONFIG_C = 'core/tf_psa_crypto_config.c'
    PROJECT_SPECIFIC_INCLUDE_DIRECTORIES = [
        'drivers/builtin/include',
    ]

    def test_crypto_no_fs_io(self) -> None:
        """A sample error expected from check_config.h."""
        self.bad_case('#undef MBEDTLS_FS_IO',
                      error=('MBEDTLS_PSA_ITS_FILE_C'))

    def test_crypto_mbedtls_config_not_read(self) -> None:
        """Check that mbedtls_config.h is not read in crypto."""
        self.good_case('',
                       '#error "mbedtls_config.h was read"')

    def test_crypto_nv_seed_only_with_entropy_no_sources_ok(self) -> None:
        """NV-seed-only configuration with MBEDTLS_ENTROPY_NO_SOURCES_OK defined
        to acknowledge that there is no true entropy source and that the
        loss of security is acceptable.
        """
        self.good_case('''
                       #undef MBEDTLS_PSA_BUILTIN_GET_ENTROPY
                       #define MBEDTLS_ENTROPY_NV_SEED
                       #define MBEDTLS_ENTROPY_NO_SOURCES_OK
                       ''')

    def test_crypto_nv_seed_only_without_entropy_no_sources_ok(self) -> None:
        """NV-seed-only configuration without MBEDTLS_ENTROPY_NO_SOURCES_OK defined
        An error expected from tf_psa_crypto_check_config.h.
        """
        self.bad_case('''
                      #undef MBEDTLS_PSA_BUILTIN_GET_ENTROPY
                      #define MBEDTLS_ENTROPY_NV_SEED
                      ''',
                      error=(r'Entropy module enabled, but no true sources'))

    def test_crypto_external_rng_with_nv_seed(self) -> None:
        """External RNG and NV seed
        An error expected from tf_psa_crypto_check_config.h.
        """
        self.bad_case('''
                      #define MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG
                      #define MBEDTLS_ENTROPY_NV_SEED
                      ''',
                      error=(
                          r'Providing a non-volatile entropy seed does not enhance the security of an external RNG' # pylint: disable=line-too-long
                      ))

if __name__ == '__main__':
    unittest.main()
