#!/usr/bin/env python3
"""Test the configuration checks generated by generate_config_checks.py.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import unittest

import scripts_path # pylint: disable=unused-import
from mbedtls_framework import unittest_config_checks


class CryptoTestConfigChecks(unittest_config_checks.TestConfigChecks):
    """TF-PSA-Crypto unit tests for config checks."""

    #pylint: disable=invalid-name # uppercase letters make sense here

    PROJECT_CONFIG_C = 'core/tf_psa_crypto_config.c'
    PROJECT_SPECIFIC_INCLUDE_DIRECTORIES = [
        'drivers/builtin/include',
    ]

    def test_crypto_no_fs_io(self) -> None:
        """A sample error expected from check_config.h."""
        self.bad_case('#undef MBEDTLS_FS_IO',
                      error=('MBEDTLS_PSA_ITS_FILE_C'))

    def test_crypto_mbedtls_config_not_read(self) -> None:
        """Check that mbedtls_config.h is not read in crypto."""
        self.good_case('',
                       '#error "mbedtls_config.h was read"')

    def test_crypto_nv_seed_only(self) -> None:
        """An error expected from tf_psa_crypto_check_config.h with an
        NV-seed-only configuration but MBEDTLS_ENTROPY_NO_SOURCES_OK not
        defined.
        """
        self.bad_case('''
                      #undef MBEDTLS_PSA_BUILTIN_GET_ENTROPY
                      #define MBEDTLS_ENTROPY_NV_SEED
                      #undef MBEDTLS_ENTROPY_NO_SOURCES_OK
                      ''',
                      error=(r'Entropy module enabled, but no true sources'))

if __name__ == '__main__':
    unittest.main()
